Add Wireless Network support with dedicated buildable
Panakotta00/FicsIt-Networks pull request #228
Opened 2022-09-10 18:31 UTC by rockfactory

This PR introduces Wireless Network Communications through a new buildable, the Wireless Access Point (WAP), which can be connected to a Radar Tower in order to receive and transmit messages over the air. 

- The WAP has an easy to use UI where pioneers can check their wireless network and detect issues, like missing Access Points, too far towers and so on.
- Messages could be transmitted only to towers which are connected to a WAP and are in range. The range is calculated using the same Formula from SF for scanning, so an higher tower as an higher range.
- The Wireless Access Point requires Crystal Oscillator to be built, keeping a parallelism with SF recipes where Oscillator is used

On the technical side:
- The `WirelessAccessPoint` code is based on the `NetworkRouter` with some adaptation. This means loops are prevented in the same way.
- The main optimization is that we cache the available connections from each Access Point (using the WirelessSubsystem which is introduced in this commit too). Even if the alghoritm itself is not optimized, we  w need to update connections only when a WAP is built / destroyed, so very unfrequently.

TODOs/bugs - maybe other PRs based even on @Panakotta00 / community feeling:
- [ ] Destroying a Radar Tower will not immediately disable communications with its connected WAP. I'd like to implement auto-dismantle so while removing the tower, you remove the WAP too.
- [ ] Currently WAP is unlocked with the same schematic for the Network Router. We could add a "Wireless Networking" schematic in the same Tier, but I feel it would be a bit lonely
- [ ] Clicking on a Tower in the WAP interact widget opens the Marker Editor
- [ ] Wireless Access Point cannot be rotated around the Radar Tower (fixed positioning while snapped)
- [ ] Check for multiplayer support. Replication should be working, but it requires testing

An UI screen:
<img width="852" alt="Satisfactory Screenshot 2022 09 10 - 17 25 19 07" src="https://user-images.githubusercontent.com/112330494/189496161-c03cdb80-49e2-4dfd-b0c3-2521d57a2a53.png">

2022-10-01 17:29 UTC, rockfactory commented
I'll share here a link to an alpha build and a temporary documentation if someone likes to test this version and help us checking everything is fine, especially in multiplayer:

Steps:
1. Research Network Connectors, it will unlock Wireless Access Point too
2. Build a radar tower, then build a wireless access point. it will snap to the tower
3. The WAP has only one connection, connect it to your local/router network
4. Do the same with another radar tower & WAP
5. Use "E" to interact with the access point - it will show a map of other radar towers and connection status, like signal strength, presence of an access point, etc. I think it's really useful to double check your network! Bonus: you can click on a radar tower to highlight in on the map. Give the radar towers a custom name (interacting with the tower itself), and its name will show on the WAP map
6. Now you should be able to send messages between the network! Remember only network messages are allowed, refer to same docs: https://docs.ficsit.app/ficsit-networks/latest/lua/guide/InterComputerCommunication.html

2022-10-04 22:22 UTC, rockfactory commented
Released another alpha (`alpha.2`, link above), which:
- Should fix a bug with multiplayer
- Fix map panning with right mouse button
- Radar Towers now require power to operate the attached Access Point

2022-10-05 00:46 UTC, rockfactory commented
Aaand [`alpha.3`](https://1drv.ms/u/s!AqQ0YW9so_5OgUPPU0CCh7xgR5UN?e=8tGol0), which allows WAP rotation with the scroll wheel plus some UI enhancements!

2022-10-19 20:11 UTC, rockfactory commented
Well, some updates. We did a lot of testing, even on Multiplayer, with Chaka (thanks for your patience!) and we fixed some bugs, plus rewrote the multiplayer bits in order to make sure it works correctly. [`alpha.6`](https://1drv.ms/u/s!AqQ0YW9so_5OgUh4j9k3G5rJUXPF?e=XLRMtO) is ready!

2022-11-09 16:04 UTC, Panakotta00 requested changes
Additionally please refrain from using the auto keyword and instead fully type them out.

Otherwise, amazing work! Well done!

2022-11-09 16:04 UTC, Panakotta00 commented on Source/FicsItNetworks/Network/Wireless/FINWirelessAccessPointConnectionData.h
> +﻿// Copyright Coffee Stain Studios. All Rights Reserved.
Mostly not true, right?

2022-11-09 16:04 UTC, Panakotta00 commented on Source/FicsItNetworks/Network/Wireless/FINWirelessRCO.cpp
> +﻿// Copyright Coffee Stain Studios. All Rights Reserved.
Untrue

2022-11-09 16:04 UTC, Panakotta00 commented on Source/FicsItNetworks/Network/Wireless/FINWirelessRCO.h
> +﻿// Copyright Coffee Stain Studios. All Rights Reserved.
untrue

2022-11-09 16:04 UTC, Panakotta00 commented on Source/FicsItNetworks/Network/Wireless/FINWirelessSubsystem.cpp
> +﻿// Copyright Coffee Stain Studios. All Rights Reserved.
untrue

2022-11-09 16:04 UTC, Panakotta00 commented on Source/FicsItNetworks/Network/Wireless/FINWirelessSubsystem.h
> +﻿// Copyright Coffee Stain Studios. All Rights Reserved.
Untrue

2022-11-09 20:44 UTC, rockfactory commented on Source/FicsItNetworks/Components/FINWirelessAccessPointHologram.h
> +#define LOCTEXT_NAMESPACE "Construct Disqualifier FIN"
I can do it without any issue, but I copied the same structure in the original one (`Source/FactoryGame/Public/FGConstructDisqualifier.h`), e.g.:

```cpp
#define LOCTEXT_NAMESPACE "Construct Disqualifiers" 
```

```cpp
UFGConstructDisqualifier() :
		mDisqfualifyingText( LOCTEXT( "UFGConstructDisqualifier", "This should never be seen!" ) ),
		mIsSoftDisqualifier( false )
	{
	}
```

Just double checking, if you prefer to switch them I'll switch them asap

2022-11-09 21:21 UTC, rockfactory commented
@Panakotta00 changes applied, tried to remove some of the `auto`s. Just le me know if the disqualifer loc namespace is ok 👍

2022-11-09 21:24 UTC, Panakotta00 commented on Source/FicsItNetworks/Components/FINWirelessAccessPointHologram.h
> +#define LOCTEXT_NAMESPACE "Construct Disqualifier FIN"
I find that as an rather odd way of grouping but on seccond thought i agree

2022-11-09 21:26 UTC, Panakotta00 approved these changes

2022-11-09 21:28 UTC, Panakotta00 commented
If you want to you can now also add credit in the authors list in the .uplugin, the Readme and the docs if you want to.
(Just your social handle and a link to some preffered place of yours)

2022-11-09 21:36 UTC, merged