Added sign Emission. Issue #283
Panakotta00/FicsIt-Networks pull request #320
Opened 2024-06-27 08:52 UTC by RozeDoyanawa

Also fixed type on background in reflection

2024-06-27 18:20 UTC, Panakotta00 requested changes

2024-06-27 18:20 UTC, Panakotta00 commented on Source/FicsItNetworks/Private/Reflection/FINStaticReflectionSource.cpp
> +BeginFunc(newTimeTable, "New Time Table", "Creates and returns a new timetable for this train.") {
Why? Is it sure safe to call NewTimeTable in parallel?

2024-06-27 21:00 UTC, RozeDoyanawa commented
Undo commit pushed

2024-06-28 06:06 UTC, Panakotta00 requested changes

2024-06-28 06:06 UTC, Panakotta00 commented on Source/FicsItNetworks/Private/Reflection/FINStaticReflectionSource.cpp
> +BeginProp(RStruct<FLinearColor>, background, "Bckground", "The background Color.") {
you sure that should not be "Background" not "Bckground"? xD

2024-06-29 10:02 UTC, Panakotta00 approved these changes

2024-06-29 10:03 UTC, merged